---
title: "DSlecture20"
author: "Hening CUi"
date: "11/29/2021"
output: github_document
---

```{r,echo = FALSE}
library (tidyverse)
library(p8105.datasets)
library(modelr)
set.seed(1)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height =6,
  out.width = "90%"
)

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

simulate data

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

plot the dataset

```{r}
sim_df_const %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_smooth(method = "lm")

sim_df_nonconst %>% 
  ggplot(aes(x, y)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
lm(y ~ x, data = sim_df_const) %>% broom::tidy()
lm(y ~ x, data = sim_df_nonconst) %>% broom::tidy()
```

## draw one bootstrap

```{r}
boot_sample = function(df){
  sample_frac(df, replace = TRUE) %>% 
    arrange(x)
}
```

check if this works

```{r}
boot_sample(sim_df_nonconst) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha= 0.3) +
  geom_smooth(method = "lm") +
  ylim(-5, 16)

```

```{r}
boot_sample(sim_df_nonconst) %>% 
  lm(y ~ x, data = .) %>% 
  broom::tidy()
```

## many sample and analysis

```{r}
boot_stramp =
  tibble(
    stramp_number = 1:1000,
    stramp_sample = rerun(1000, boot_sample(sim_df_nonconst))
  )
```

run analysis

```{r}
bootresult =
  boot_stramp %>% 
  mutate(
    models = map(.x = stramp_sample, ~lm(y ~ x, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(stramp_number, results) %>% 
  unnest(results)
```

what do i have now

```{r}
bootresult %>% 
  group_by(term) %>% 
  summarize(
    mean_es = mean(estimate),
    sd_es = sd(estimate)
  )
```
look at the distribution
```{r}
bootresult %>% 
  filter(term == "x") %>% 
  ggplot(aes(x = estimate)) +
  geom_density() 
```

construct bootstrap CI

```{r}
bootresult %>% 
  group_by(term) %>% 
  summarize(
    ci_lower = quantile(estimate, 0.025),
    ci_upper = quantile(estimate,0.975)
  )
```
## bootstrap using modelr

can we simplify anything

```{r}
sim_df_nonconst %>% 
  bootstrap(1000, id = "stramp_number")%>% 
  mutate(
    models = map(.x = strap, ~lm(y ~ x, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(stramp_number, results) %>% 
  unnest(results) %>% 
  group_by(term) %>% 
  summarize(
    mean_es = mean(estimate),
    sd_es = sd(estimate)
  )
```

```{r}
boot_stramp %>% 
  unnest(stramp_sample) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_line(aes(group = stramp_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = sim_df_nonconst, alpha = .5)
```

## revisit nyc airbnb

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  drop_na(price, stars) %>% 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
nyc_airbnb %>% 
  ggplot(aes( x = stars, y = price)) +
  geom_point()
```

```{r}
air_boot =
  nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  drop_na(stars) %>% 
  bootstrap(1000, id = "stramp_number")%>% 
  mutate(
    models = map(.x = strap, ~lm(price ~ stars, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(stramp_number, results) %>% 
  unnest(results)
```


```{r}
air_boot %>% 
  group_by(term) %>% 
  summarize(
    mean_es = mean(estimate),
    sd_es = sd(estimate)
  )
```

compare to lm

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  drop_na(stars) %>%
  lm(price ~ stars, data = .) %>% 
  broom::tidy()
```
```{r}
air_boot %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) +
  geom_density()
```

